data-source:
  file:
    location: ./file-from-tsbs-generate-data
  type: FILE
loader:
  db-specific:
    debug: 0
    host: localhost
    log-batches: false
    password: ""
    user: default
  runner:
    batch-size: "10000"
    channel-capacity: "0"
    db-name: benchmark
    do-abort-on-exist: false
    do-create-db: true
    do-load: true
    flow-control: false
    hash-workers: false
    insert-intervals: ""
    limit: "0"
    reporting-period: 10s
    seed: 0
    workers: "1"
  target: clickhouse
